---
ansible_user: ansible
ansible_connection: netconf 
ansible_network_os: junos

log_host: 10.100.102.254

tacacs:
  ipv4: 192.0.2.1
  secret: supersecret

snmp:
  location: Ansible Home
  contact: Ansible
  user: ansible
  group: ansible_group
