---
all:
  children:
    edge:
    inter:
  vars:
    ansible_user: devbox
    ansible_ssh_private_key_file: ~/.ssh/nac
    ansible_network_os: junipernetworks.junos.junos

edge:
  hosts:
    edge_r1:
      ansible_host: 10.1.3.2
    edge_r2:
      ansible_host: 10.1.2.2

inter:
  hosts:
    inter_r1:
      ansible_host: 10.1.4.2
    inter_r2:
      ansible_host: 10.1.5.2
