---
- name: Configure Prefix Lists 
  junipernetworks.junos.junos_config:
    src: prefixlists.j2
  when:
    - route_policies is defined
    - route_policies.prefix_lists is defined
  tags:
    - bgp
    - bgp_v4
    - bgp_v6

- name: Configure Route Policies 
  junipernetworks.junos.junos_config:
    src: policies.j2
  when:
    - route_policies is defined
    - route_policies.rp is defined
  tags:
    - bgp
    - bgp_v4
    - bgp_v6

- name: Configure BGP Peers
  junipernetworks.junos.junos_config:
    src: bgp_group.j2
  when:
    - bgp is defined
  tags:
    - bgp
    - bgp_v4
    - bgp_v6
