---
- name: "Get Junos OS configuration"
  hosts: junos
  connection: local
  gather_facts: no

  tasks:
    - name: "Save configuration to a file"
      juniper.device.config:
        retrieve: "committed"
        format: "set"
        dest_dir: "../backups"
