---
# tasks file for junos_interface

- name: Configure subinterfaces
  junipernetworks.junos.junos_config:
    src: subinterfaces.j2
    src_format: set

- name: Configure interface status and descriptions
  junipernetworks.junos.junos_interfaces:
    config:
      - name: "{{ item.name }}"
        description: "{{ item.desc }}"
        enabled: "{{ item.enabled }}"
  when: item.unit == 0
  loop: "{{ interfaces }}"

- name: Configure Layer 3 interfaces
  junipernetworks.junos.junos_l3_interfaces:
    config:
      - name: "{{ item.name }}"
        unit: "{{ item.unit }}"
        ipv4:
        - address: "{{ item.ipv4_addr }}"
  when: 
    - item.ipv4_addr is defined
  loop: "{{ interfaces }}"

- name: Configure Layer 3 IPv6 interfaces
  junipernetworks.junos.junos_l3_interfaces:
    config:
      - name: "{{ item.name }}"
        unit: "{{ item.unit }}"
        ipv6:
        - address: "{{ item.ipv6_addr }}"
  when:
    - item.ipv6_addr is defined
  loop: "{{ interfaces }}"
