---
- name: "Compare configurations"
  hosts: junos 
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "ROLLBACK"
      prompt: "Rollback ID to compare with active configuration" 
      private: false

  tasks:
    - name: "Compare active to previous configuration and save to a file"
      juniper.device.config:
        diff: true
        rollback: "{{ ROLLBACK }}"    
        check: false
        commit: false
        # Save diffs to a file:
        diffs_file: "../diffs/{{ inventory_hostname }}-diff-rollback-{{ ROLLBACK }}"
      register: diff
    - name: "Print diff"
      ansible.builtin.debug:
        var: diff
