---
- name: "Get Junos OS configuration"
  hosts: edge
  connection: local
  gather_facts: no

  tasks:
    - name: "Save configuration to a file"
      juniper.device.config:
        retrieve: "committed"
        format: "text"
        save_dir: "../../batfish/configs"
