---
# tasks file for pre_tasks

- name: "Check if the builds/{{ inventory_hostname }}.conf file exists"
  ansible.builtin.stat:
    path: "{{ base_dir }}/builds/{{ inventory_hostname }}.conf"
  register: build

- name: "Remove the contents of builds/{{ inventory_hostname }}.conf file if it exists"
  ansible.builtin.shell: "cat /dev/null > {{ base_dir }}/builds/{{ inventory_hostname }}.conf"
  when: build.stat.exists

- name: "Recreate builds/{{ inventory_hostname }}.conf empty file if it does not exist"
  ansible.builtin.file:
    path: "{{ base_dir }}/builds/{{ inventory_hostname }}.conf"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"
    state: touch
  when: not build.stat.exists
