router_id: 192.0.2.202
rtr_role: internal
addressbook:
  - zone: internal
    name: edge-rtr
    ip: 192.0.2.102
    set: 
    - internal_bgp_peers
    - internal-rtr-loop
  - zone: internal
    name: edge-rtr-v6
    ip: "2001:db8:902:beef::1/128"
    set: 
    - internal_bgp_peers
    - internal-rtr-loop
fw_policies:
  - name: all_icmp
    zone: global
    source: any
    destination: any
    action: permit
    apps:
      - junos-ping
  - name: a_int_bgp
    zone: internal
    from_zone: internal
    to_zone: internal
    source: 
      - internal_bgp_peers
    destination: any
    action: permit
    apps:
      - junos-bgp
  - name: a_int_bgp_host
    zone: internal
    from_zone: internal
    to_zone: junos-host
    source: 
      - internal_bgp_peers
    destination: any
    action: permit
    apps:
      - junos-bgp
route_policies:
  prefix_lists:
    - name: external_nets
      addresses:
         - 192.0.2.1/32
         - "2001:db8:999:beef::1/128"
         - 10.100.102.0/24
    - name: internal_nets
      addresses:
         - 192.0.2.102/32
         - 192.0.2.202/32
         - 10.100.202.0/24
         - "2001:db8:902:beef::1/128"
         - "2001:db8:902:beef::2/128"
         - "2001:db8:902::/64"
    - name: default_route
      addresses:
        - 0.0.0.0/0
  rp:
    - name: external_networks
      from:
        protocols: 
        - bgp
        pfx_list: external_nets
      action: accept
    - name: internal_networks
      from:
        protocols:
        - bgp
        pfx_list: internal_nets
      action: accept
    - name: default_route
      from:
        protocols: 
        - bgp 
        pfx_list: default_route
      action: accept
    - name: deny-all 
      action: reject
bgp:
  local_as: 65102
  groups:
    - name: IBGP
      type: internal
      desc: "IBGP BGP Peering"
      hold: 30
      policies:
        export:
          - internal_networks 
          - deny-all
        import: 
          - internal_networks
          - external_networks
          - default_route
          - deny-all
      neighbours:
        - peer: 192.0.2.102
          loc_ip: 192.0.2.202
          desc: "junos-02 IPv4"
        - peer: "2001:db8:902:beef::1"
          loc_ip: "2001:db8:902:beef::2"
          desc: "junos-02 IPv6"
zones:
  - name: "internal"
    host_traffic:
      protocols:
        - bgp
        - ospf
        - ospf3
      services:
        - ping
        - traceroute
interfaces:
  - junos_if: "fxp0"
    unit: 0
    desc: "Management"
    enabled: "true"
    ipv4_addr: "10.15.30.34/24"
  - junos_if: "ge-0/0/0"
    unit: 0
    desc: "VLAN Bridge"
    enabled: "true"
    subint:
      vlans:
      - 202
  - junos_if: "ge-0/0/0"
    unit: 202
    desc: "To junos-01"
    enabled: "true"
    ipv4_addr: "10.100.202.253/24"
    ipv6_addr: "2001:db8:202::f/64"
    if_zone: "internal"
    ospf:
      area: "0.0.0.0"
    ospfv3:
      area: "0.0.0.0"
  - junos_if: "lo0"
    unit: 0
    desc: "Loopback"
    enabled: "true"
    if_zone: "internal"
    ipv4_addr: "192.0.2.202/32"
    ipv6_addr: "2001:db8:902:beef::2/128"
    ospf:
      area: "0.0.0.0"
      passive: true
    ospfv3:
      area: "0.0.0.0"
      passive: true
