router_id: 192.0.2.102
rtr_role: edge
addressbook:
  - zone: edge
    name: netsvr
    ip: 10.100.102.254
    set:
      - external_bgp_peers
      - netsvr-direct
  - zone: edge
    name: netsvr-v6
    ip: "2001:db8:102::ffff/128"
    set:
      - external_bgp_peers
      - netsvr-direct
  - zone: edge
    name: netsvr-lo
    ip: 192.0.2.1
    set:
    - netsvr-loop
  - zone: edge
    name: netsvr-lo-v6
    ip: "2001:db8:999:beef::1/128"
    set: 
    - netsvr-loop
  - zone: internal
    name: internal-rtr
    ip: 192.0.2.202
    set: 
    - internal_bgp_peers
    - internal-rtr-loop
  - zone: internal
    name: internal-rtr-v6
    ip: "2001:db8:902:beef::2/128"
    set: 
    - internal_bgp_peers
    - internal-rtr-loop
fw_policies:
  - name: all_icmp
    zone: global
    source: any
    destination: any
    action: permit
    apps:
      - junos-ping
  - name: a_tacacs
    zone: internal
    from_zone: internal
    to_zone: edge
    source: any
    destination: 
      - netsvr-loop
    action: permit
    apps:
      - junos-tacacs
  - name: a_syslog
    zone: internal
    from_zone: internal
    to_zone: edge
    source: any
    destination: 
      - netsvr-direct
    action: permit
    apps:
      - junos-syslog
  - name: a_ext_bgp
    zone: edge
    from_zone: edge
    to_zone: edge
    source: 
      - external_bgp_peers
    destination: any
    action: permit
    apps:
      - junos-bgp
  - name: a_ext_bgp_host
    zone: edge
    from_zone: edge
    to_zone: junos-host
    source: 
      - external_bgp_peers
    destination: any
    action: permit
    apps:
      - junos-bgp
  - name: a_int_bgp
    zone: internal
    from_zone: internal
    to_zone: internal
    source: 
      - internal_bgp_peers
    destination: any
    action: permit
    apps:
      - junos-bgp
  - name: a_int_bgp_host
    zone: internal
    from_zone: internal
    to_zone: junos-host
    source: 
      - internal_bgp_peers
    destination: any
    action: permit
    apps:
      - junos-bgp
  - name: a_internet_routing
    zone: internal
    from_zone: internal
    to_zone: internal
    source: any
    destination: any
    action: permit
    apps: any
route_policies:
  prefix_lists:
    - name: internal_nets
      addresses:
         - 192.0.2.102/32
         - 192.0.2.202/32
         - 10.100.202.0/24
         - "2001:db8:902:beef::1/128"
         - "2001:db8:902:beef::2/128"
         - "2001:db8:902::/64"
    - name: external_nets
      addresses:
         - 192.0.2.1/32
         - "2001:db8:999:beef::1/128"
         - 10.100.102.0/24
  rp:
    - name: external_networks
      from:
        protocols: 
        - bgp
        pfx_list: external_nets
      action: accept
    - name: internal_networks
      from:
        protocols:
        - direct
        - ospf
        - ospf3
        pfx_list: internal_nets
      action: accept
    - name: dhcp_default
      from:
        protocols: 
        - access-internal
      action: accept
    - name: deny-all 
      action: reject
bgp:
  local_as: 65102
  groups:
    - name: NETSVR
      type: external
      desc: "Peering to NETSVR"
      hold: 30
      policies:
        import:
          - external_networks
          - deny-all
        export: 
          - internal_networks
          - deny-all
      neighbours:
        - peer: 10.100.102.254
          remote_as: 65430
          desc: "netsvr-01 IPv4"
        - peer: "2001:db8:102::ffff"
          remote_as: 65430
          desc: "netsvr-01 IPv6"
    - name: IBGP
      type: internal
      desc: "IBGP BGP Peering"
      hold: 30
      policies:
        export:
          - dhcp_default
          - external_networks
          - deny-all
        import: 
          - internal_networks
          - deny-all
      neighbours:
        - peer: 192.0.2.202
          loc_ip: 192.0.2.102
          default_originate: true
          desc: "junos-02 IPv4"
        - peer: "2001:db8:902:beef::2"
          loc_ip: "2001:db8:902:beef::1"
          desc: "junos-02 IPv6"
zones:
  - name: "edge"
    host_traffic:
      protocols:
        - bgp
      services:
        - ping
        - traceroute
  - name: "internet"
    nat: 
      role: "outside"
    host_traffic:
      services:
        - ping
        - traceroute
        - dhcp
  - name: "internal"
    nat:
      role: "inside"
    host_traffic:
      protocols:
        - bgp
        - ospf
        - ospf3
      services:
        - ping
        - traceroute
interfaces:
  - junos_if: "fxp0"
    unit: 0
    desc: "Management"
    enabled: "true"
    ipv4_addr: "10.15.30.33/24"
  - junos_if: "ge-0/0/0"
    unit: 0
    desc: "VLAN Bridge"
    enabled: "true"
    subint:
      vlans:
      - 102
      - 202
  - junos_if: "ge-0/0/0"
    unit: 102
    desc: "To netsvr"
    enabled: "true"
    if_zone: "edge"
    ipv4_addr: "10.100.102.253/24"
    ipv6_addr: "2001:db8:102::f/64"
    ospf:
      area: "0.0.0.0"
      passive: true
    ospfv3:
      area: "0.0.0.0"
      passive: true
  - junos_if: "ge-0/0/0"
    unit: 202
    desc: "To junos-02"
    enabled: "true"
    ipv4_addr: "10.100.202.254/24"
    ipv6_addr: "2001:db8:202::a/64"
    if_zone: "internal"
    ospf:
      area: "0.0.0.0"
    ospfv3:
      area: "0.0.0.0"
  - junos_if: "ge-0/0/1"
    desc: "To the Internet"
    unit: 0
    enabled: "true"
    ipv4_addr: "dhcp"
    if_zone: "internet"
    ospf:
      area: "0.0.0.0"
      passive: true
  - junos_if: "lo0"
    unit: 0
    desc: "Loopback"
    enabled: "true"
    if_zone: "internal"
    ipv4_addr: "192.0.2.102/32"
    ipv6_addr: "2001:db8:902:beef::1/128"
    ospf:
      area: "0.0.0.0"
      passive: true
    ospfv3:
      area: "0.0.0.0"
      passive: true
