---
# Ref: https://www.juniper.net/documentation/us/en/software/junos-ansible/ansible/topics/topic-map/junos-ansible-connection-methods.html

- name: Load Initial Configuration
  hosts: junos
  connection: local
  gather_facts: false

  vars_prompt:
    - name: "DEVICE_PASSWORD"
      prompt: "Device Password"
      private: yes

  tasks:
    - name: Load initial configuration and commit
      juniper.device.config:
        passwd: "{{ DEVICE_PASSWORD }}"
        mode: "serial"
        # Default port: /dev/ttyUSB0
        port: "/dev/ttyUSB0"
        load: "override"
        format: set
        commit: true
        src: "../builds/junos_init.set"
        comment: "[ Configured by Ansible ]"
      register: response
    - name: Print the response
      ansible.builtin.debug:
        var: response
