---
# tasks file for junos_system

- name: Set hostname
  junipernetworks.junos.junos_system:
    hostname: "{{ inventory_hostname }}"

- name: Configure syslog
  junipernetworks.junos.junos_logging:
    dest: host
    name: "{{ syslog_host }}"
    level: info
    facility: any
    state: present
